services:
  ubuntu-torch-service:
    image: ubuntu-torch
    volumes: 
      - C:\Users\Cassio\Projetos\Pesquisa:/home/ubuntu/dev
    tty: true
    stdin_open: true 
    network_mode: "host"
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all # alternatively, use `count: all` for all GPUs
                capabilities: [gpu]